Message: invalid argument
  (Session info: chrome=98.0.4758.102)
Stacktrace:
0   chromedriver                        0x000000010a69f3c9 chromedriver + 5018569
1   chromedriver                        0x000000010a62a333 chromedriver + 4539187
2   chromedriver                        0x000000010a1ff93f chromedriver + 170303
3   chromedriver                        0x000000010a1ebc36 chromedriver + 89142
4   chromedriver                        0x000000010a1ea924 chromedriver + 84260
5   chromedriver                        0x000000010a1eaa43 chromedriver + 84547
6   chromedriver                        0x000000010a20149e chromedriver + 177310
7   chromedriver                        0x000000010a264de1 chromedriver + 585185
8   chromedriver                        0x000000010a2517e2 chromedriver + 505826
9   chromedriver                        0x000000010a264604 chromedriver + 583172
10  chromedriver                        0x000000010a2516d3 chromedriver + 505555
11  chromedriver                        0x000000010a22795e chromedriver + 334174
12  chromedriver                        0x000000010a228935 chromedriver + 338229
13  chromedriver                        0x000000010a65b1ee chromedriver + 4739566
14  chromedriver                        0x000000010a674f51 chromedriver + 4845393
15  chromedriver                        0x000000010a67a928 chromedriver + 4868392
16  chromedriver                        0x000000010a675a7a chromedriver + 4848250
17  chromedriver                        0x000000010a64fc31 chromedriver + 4693041
18  chromedriver                        0x000000010a690978 chromedriver + 4958584
19  chromedriver                        0x000000010a690b01 chromedriver + 4958977
20  chromedriver                        0x000000010a6a6795 chromedriver + 5048213
21  libsystem_pthread.dylib             0x00007fff67bf1109 _pthread_start + 148
22  libsystem_pthread.dylib             0x00007fff67becb8b thread_start + 15

HTTPConnectionPool(host='localhost', port=57633): Max retries exceeded with url: /session/99901fbf510603e669ad759a551e0563/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10733e7c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
